export const allTopics = [
  'python',
  'software development',
  'artificial intelligence',
  'web development',
  'programming',
  'data science',
  'technology',
  'humor',
  'deep learning',
  'machine learning',
  'marketing',
  'blockchain',
  'coding',
  'react',
  'work',
  'society',
  'lifestyle',
  'web3',
  'java',
  'math',
  'space',
  'sports',
  'media',
  'docker',
  'race',
  'music',
  'justice',
  'gaming',
] as const

export type TopicsType = (typeof allTopics)[number]
